spring:
  application:
    name: employee-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Bajaj@2023
    driver: io.r2dbc.postgresql.PostgreSQLConnectionFactoryProvider

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 3333
